import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '../shared/styles/globals.css';
import { AuthProvider } from '@/shared/contexts/auth/auth.provider';
import { Navbar } from '@/shared/components/common/navbar';
import { DrawerCSSProvider } from '@/shared/providers/drawer-css.provider';
import { QueryClientProvider } from '@/shared/providers/react-quer.provider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br" className="bg-white">
      <QueryClientProvider>
        <AuthProvider>
          <body className={`${inter.className} bg-white`}>
            <DrawerCSSProvider>
              <Navbar />
              {children}
            </DrawerCSSProvider>
          </body>
        </AuthProvider>
      </QueryClientProvider>
    </html>
  );
}
